[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "geneharmony"
description = "Async toolkit to normalize gene identifiers and annotate gene sets with data from the Alliance of Genome Resources (AGR) or user-ingested datasets."
readme = "README.md"
requires-python = ">=3.14"
license = "MIT"
authors = [
    {name = "Lionel Sequeira", email = "lionelsequeira@gmail.com"} 
]
dynamic = ["version"]
dependencies = [
    "httpx",
    "pydantic",
    "pandas",
    "pyarrow"
]

[tool.hatch.version]
path = "src/geneharmony/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/geneharmony"]